print("handling exception")
try:
    print(x)
except:
    print("an exception occur")